import { invokeAi } from './ai'

export const APTITUDE_CATEGORIES = [
  {
    id: 'quant',
    title: 'Quantitative Aptitude',
    description: 'Percentages, Speed & Distance, Profit & Loss, Work & Time, Interest, Probability & Algebra.',
    icon: 'Calculator',
    count: 20,
  },
  {
    id: 'logical',
    title: 'Logical Reasoning',
    description: 'Coding-Decoding, Blood Relations, Syllogisms, Series, Directions, Seating & Venn Diagrams.',
    icon: 'Brain',
    count: 20,
  },
  {
    id: 'verbal',
    title: 'Verbal Ability',
    description: 'Reading Comprehension, Synonyms & Antonyms, Idioms, Substitutions, Grammar & Voice.',
    icon: 'MessageSquare',
    count: 20,
  },
  {
    id: 'technical',
    title: 'Technical & CS Fundamentals',
    description: 'OOPs concepts, OS, DBMS, Computer Networks, Data Structures & Algorithm MCQs.',
    icon: 'Code2',
    count: 20,
  },
]

export const SAMPLE_QUESTIONS = {
  quant: [
    {
      id: 'q1',
      question: 'A train 240 m long passes a pole in 24 seconds. What is the speed of the train in km/hr?',
      options: ['30 km/hr', '36 km/hr', '40 km/hr', '48 km/hr'],
      correct: 1,
      explanation: 'Speed = Distance / Time = 240m / 24s = 10 m/s. Convert to km/hr = 10 * (18/5) = 36 km/hr.',
    },
    {
      id: 'q2',
      question: 'If a product is sold at a 20% profit for $120, what was its original cost price?',
      options: ['$90', '$100', '$105', '$110'],
      correct: 1,
      explanation: 'Cost Price * 1.20 = 120. Therefore, Cost Price = 120 / 1.20 = $100.',
    },
    {
      id: 'q3',
      question: 'A and B can complete a work in 10 days and 15 days respectively. Working together, how many days will they take?',
      options: ['5 days', '6 days', '7.5 days', '8 days'],
      correct: 1,
      explanation: 'Work rate per day = 1/10 + 1/15 = 5/30 = 1/6. Total days required = 6 days.',
    },
    {
      id: 'q4',
      question: 'What is the simple interest earned on $5,000 at 8% per annum for 3 years?',
      options: ['$1,000', '$1,200', '$1,400', '$1,500'],
      correct: 1,
      explanation: 'Simple Interest = (Principal * Rate * Time) / 100 = (5000 * 8 * 3) / 100 = $1,200.',
    },
    {
      id: 'q5',
      question: 'Two dice are thrown together. What is the probability that the sum of numbers on the dice is 7?',
      options: ['1/36', '1/12', '1/6', '5/36'],
      correct: 2,
      explanation: 'Favorable outcomes (1+6, 2+5, 3+4, 4+3, 5+2, 6+1) = 6 out of 36. Probability = 6/36 = 1/6.',
    },
    {
      id: 'q6',
      question: 'The average age of a class of 20 students is 15 years. When the teacher’s age is added, the average increases by 1 year. What is the teacher’s age?',
      options: ['34 years', '36 years', '35 years', '40 years'],
      correct: 1,
      explanation: 'Initial sum = 20 * 15 = 300. New sum (21 people * 16 average) = 336. Teacher age = 336 - 300 = 36 years.',
    },
    {
      id: 'q7',
      question: 'A ratio of 4:5 converted to percentage is equal to:',
      options: ['60%', '75%', '80%', '85%'],
      correct: 2,
      explanation: '(4 / 5) * 100 = 80%.',
    },
    {
      id: 'q8',
      question: 'How many different ways can the letters of the word "LEADER" be arranged?',
      options: ['360', '720', '180', '120'],
      correct: 0,
      explanation: 'Word has 6 letters with E repeating twice. Total permutations = 6! / 2! = 720 / 2 = 360.',
    },
    {
      id: 'q9',
      question: 'A car covers a distance of 300 km in 5 hours. What is its average speed in m/s?',
      options: ['15 m/s', '16.67 m/s', '20 m/s', '25 m/s'],
      correct: 1,
      explanation: 'Speed = 300/5 = 60 km/hr. Convert to m/s = 60 * (5/18) = 16.67 m/s.',
    },
    {
      id: 'q10',
      question: 'If 15% of a number is 45, what is 40% of that number?',
      options: ['100', '120', '150', '160'],
      correct: 1,
      explanation: 'Number = 45 / 0.15 = 300. 40% of 300 = 120.',
    },
    {
      id: 'q11',
      question: 'What is the compound interest on $10,000 for 2 years at 10% per annum compounded annually?',
      options: ['$2,000', '$2,100', '$2,200', '$2,500'],
      correct: 1,
      explanation: 'Amount = 10000 * (1.10)^2 = 12100. CI = 12100 - 10000 = $2,100.',
    },
    {
      id: 'q12',
      question: 'A pipe can fill a tank in 6 hours and another pipe can empty it in 8 hours. If both are opened together, how long will it take to fill the tank?',
      options: ['12 hours', '18 hours', '24 hours', '30 hours'],
      correct: 2,
      explanation: 'Net filling rate = 1/6 - 1/8 = (4 - 3)/24 = 1/24. Time required = 24 hours.',
    },
    {
      id: 'q13',
      question: 'The HCF of two numbers is 11 and their LCM is 7700. If one number is 275, find the other.',
      options: ['275', '308', '318', '350'],
      correct: 1,
      explanation: 'Number 1 * Number 2 = HCF * LCM. 275 * N2 = 11 * 7700 => N2 = 84700 / 275 = 308.',
    },
    {
      id: 'q14',
      question: 'A card is drawn at random from a standard deck of 52 cards. What is the probability of getting a King or a Queen?',
      options: ['1/13', '2/13', '4/13', '1/26'],
      correct: 1,
      explanation: 'There are 4 Kings and 4 Queens = 8 cards total. Probability = 8/52 = 2/13.',
    },
    {
      id: 'q15',
      question: 'Find the area of a circle whose circumference is 44 cm. (Take pi = 22/7)',
      options: ['154 cm²', '144 cm²', '164 cm²', '174 cm²'],
      correct: 0,
      explanation: '2 * (22/7) * r = 44 => r = 7 cm. Area = (22/7) * 7 * 7 = 154 cm².',
    },
    {
      id: 'q16',
      question: 'A seller marks an item 30% above cost price and offers a 10% discount. What is his profit percentage?',
      options: ['17%', '20%', '23%', '25%'],
      correct: 0,
      explanation: 'Selling Price = 130 * 0.90 = 117. Profit % = 117 - 100 = 17%.',
    },
    {
      id: 'q17',
      question: 'If the side of a square is increased by 20%, by what percentage does its area increase?',
      options: ['20%', '40%', '44%', '48%'],
      correct: 2,
      explanation: 'New Area = (1.20)^2 = 1.44 = 44% increase.',
    },
    {
      id: 'q18',
      question: 'In what ratio must water be mixed with milk costing $12 per liter so that the mixture costs $10 per liter?',
      options: ['1:5', '1:6', '1:4', '2:5'],
      correct: 0,
      explanation: 'By Alligation: (12 - 10) : (10 - 0) = 2 : 10 = 1 : 5.',
    },
    {
      id: 'q19',
      question: 'Solve for x: 3^(x + 2) = 81',
      options: ['1', '2', '3', '4'],
      correct: 1,
      explanation: '81 = 3^4. Therefore x + 2 = 4 => x = 2.',
    },
    {
      id: 'q20',
      question: 'Three numbers are in the ratio 1:2:3 and their sum is 180. What is the largest number?',
      options: ['60', '80', '90', '100'],
      correct: 2,
      explanation: '1x + 2x + 3x = 180 => 6x = 180 => x = 30. Largest number = 3 * 30 = 90.',
    },
  ],

  logical: [
    {
      id: 'l1',
      question: 'Find the next number in the series: 2, 6, 12, 20, 30, ?',
      options: ['40', '42', '44', '48'],
      correct: 1,
      explanation: 'Differences between consecutive terms are +4, +6, +8, +10. Next difference is +12. 30 + 12 = 42.',
    },
    {
      id: 'l2',
      question: 'If "CAT" is coded as 3120, how is "DOG" coded?',
      options: ['4157', '41515', '4147', '4158'],
      correct: 0,
      explanation: 'Letters correspond to alphabetical positions: C=3, A=1, T=20 -> 3120. D=4, O=15, G=7 -> 4157.',
    },
    {
      id: 'l3',
      question: 'Pointing to a photograph, Rohan said, "She is the daughter of my grandfather’s only son." How is the girl related to Rohan?',
      options: ['Sister', 'Cousin', 'Aunt', 'Mother'],
      correct: 0,
      explanation: 'Rohan’s grandfather’s only son is Rohan’s father. The daughter of Rohan’s father is Rohan’s sister.',
    },
    {
      id: 'l4',
      question: 'Statements: All cats are animals. All animals are mammals. Conclusion: All cats are mammals.',
      options: ['Follows', 'Does not follow', 'Either follows or not', 'Neither follows'],
      correct: 0,
      explanation: 'Since Cats ⊂ Animals and Animals ⊂ Mammals, it directly follows that Cats ⊂ Mammals.',
    },
    {
      id: 'l5',
      question: 'A person walks 5 km North, then turns Right and walks 3 km, then turns Right and walks 5 km. How far is he from the starting point?',
      options: ['3 km East', '3 km West', '5 km South', '8 km East'],
      correct: 0,
      explanation: '5 km North cancel out by 5 km South. The remaining offset is 3 km East.',
    },
    {
      id: 'l6',
      question: 'Which word does NOT belong with the others?',
      options: ['Leopard', 'Cougar', 'Elephant', 'Cheetah'],
      correct: 2,
      explanation: 'Leopard, Cougar, and Cheetah belong to the Felidae (cat) family; Elephant does not.',
    },
    {
      id: 'l7',
      question: 'Doctor : Hospital :: Teacher : ?',
      options: ['Office', 'School', 'Library', 'University'],
      correct: 1,
      explanation: 'A doctor works in a hospital; a teacher primarily works in a school.',
    },
    {
      id: 'l8',
      question: 'Find the odd pair out:',
      options: ['Gold : Ornament', 'Wood : Furniture', 'Leather : Shoes', 'Cloth : Tailor'],
      correct: 3,
      explanation: 'In the first three pairs, raw material -> finished product. Tailor is a person, not a product.',
    },
    {
      id: 'l9',
      question: 'Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?',
      options: ['7', '10', '12', '13'],
      correct: 1,
      explanation: 'Alternating pattern: +3, -2, +3, -2. 12 - 2 = 10.',
    },
    {
      id: 'l10',
      question: 'If SOUTH-EAST becomes NORTH, NORTH-EAST becomes WEST, what will WEST become?',
      options: ['SOUTH-EAST', 'NORTH-WEST', 'SOUTH-WEST', 'EAST'],
      correct: 0,
      explanation: 'Every direction rotates 135 degrees anti-clockwise. WEST rotated 135 degrees anti-clockwise becomes SOUTH-EAST.',
    },
    {
      id: 'l11',
      question: 'If A + B means A is the brother of B; A - B means A is the sister of B, what does P + Q - R mean?',
      options: ['P is brother of R', 'P is sister of R', 'P is father of R', 'P is uncle of R'],
      correct: 0,
      explanation: 'P is brother of Q, and Q is sister of R. Therefore P is the brother of R.',
    },
    {
      id: 'l12',
      question: 'Find the missing term in the sequence: Z, W, T, Q, ?',
      options: ['N', 'O', 'P', 'M'],
      correct: 0,
      explanation: 'Alphabetical positions decrease by 3: Z(26), W(23), T(20), Q(17), N(14).',
    },
    {
      id: 'l13',
      question: 'Statements: Some books are pens. No pen is a pencil. Conclusion I: Some books are not pencils. Conclusion II: No book is a pencil.',
      options: ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'],
      correct: 0,
      explanation: 'Books that are pens cannot be pencils, so Conclusion I definitely follows.',
    },
    {
      id: 'l14',
      question: 'In a class of 45 students, Rahul rank is 15th from the top. What is his rank from the bottom?',
      options: ['30th', '31st', '32nd', '29th'],
      correct: 1,
      explanation: 'Rank from bottom = Total - Rank from top + 1 = 45 - 15 + 1 = 31st.',
    },
    {
      id: 'l15',
      question: 'If Monday falls on the 1st of a month, which day falls on the 25th of the same month?',
      options: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
      correct: 0,
      explanation: '(25 - 1) = 24 days. 24 % 7 = 3 odd days. Monday + 3 days = Thursday.',
    },
    {
      id: 'l16',
      question: 'Find the missing number in the matrix: [2, 4, 8; 3, 9, 27; 4, 16, ?]',
      options: ['32', '64', '48', '52'],
      correct: 1,
      explanation: 'Row pattern is n, n^2, n^3. 4, 4^2 = 16, 4^3 = 64.',
    },
    {
      id: 'l17',
      question: 'Which diagram represents the relationship between: Authors, Teachers, and Humans?',
      options: [
        'Three separate circles',
        'Two overlapping circles inside a large circle',
        'One circle inside another',
        'Three concentric circles',
      ],
      correct: 1,
      explanation: 'Both Authors and Teachers are Humans (large outer circle), and some Humans can be both Authors and Teachers (overlapping inner circles).',
    },
    {
      id: 'l18',
      question: 'If "MONKEY" is coded as "XDJMNL", how is "TIGER" coded?',
      options: ['QDFHS', 'SDFHS', 'SHFDQ', 'UJHFS'],
      correct: 0,
      explanation: 'Each letter is replaced by its predecessor and reversed.',
    },
    {
      id: 'l19',
      question: 'Five people A, B, C, D, E are sitting in a row facing North. C is sitting next to E and D. B is at the extreme right end. A is at the extreme left. Who is sitting in the middle?',
      options: ['C', 'D', 'E', 'B'],
      correct: 0,
      explanation: 'Seating order: A - E - C - D - B. C is in the middle.',
    },
    {
      id: 'l20',
      question: 'If 2 + 3 = 10, 3 + 4 = 21, 4 + 5 = 36, then 5 + 6 = ?',
      options: ['50', '55', '60', '65'],
      correct: 1,
      explanation: 'Pattern: a * (a + b). 2 * (2+3) = 10, 3 * (3+4) = 21, 4 * (4+5) = 36, 5 * (5+6) = 55.',
    },
  ],

  verbal: [
    {
      id: 'v1',
      question: 'Select the synonym for "METICULOUS":',
      options: ['Careless', 'Painstaking', 'Hasty', 'Vague'],
      correct: 1,
      explanation: 'Meticulous means showing great attention to detail; careful and precise (synonym: painstaking).',
    },
    {
      id: 'v2',
      question: 'Select the antonym for "EPHEMERAL":',
      options: ['Transient', 'Permanent', 'Fleeting', 'Short-lived'],
      correct: 1,
      explanation: 'Ephemeral means lasting for a very short time; its antonym is permanent or everlasting.',
    },
    {
      id: 'v3',
      question: 'Choose the correct one-word substitution: "One who knows everything":',
      options: ['Omnipotent', 'Omnipresent', 'Omniscient', 'Optimist'],
      correct: 2,
      explanation: 'Omniscient means all-knowing. (Omnipotent = all-powerful, Omnipresent = present everywhere).',
    },
    {
      id: 'v4',
      question: 'Identify the meaning of the idiom: "Spill the beans"',
      options: ['To drop food', 'To reveal a secret prematurely', 'To perform magic', 'To spend money recklessly'],
      correct: 1,
      explanation: '"Spill the beans" is an idiom meaning to reveal secret information accidentally or prematurely.',
    },
    {
      id: 'v5',
      question: 'Fill in the blank: "She has been working on this project _____ 2022."',
      options: ['for', 'since', 'from', 'during'],
      correct: 1,
      explanation: '"Since" is used to refer to a specific point in past time up to the present.',
    },
    {
      id: 'v6',
      question: 'Choose the correctly spelled word:',
      options: ['Accommodate', 'Acommodate', 'Accomodate', 'Acocommodate'],
      correct: 0,
      explanation: 'The correct spelling is ACCOMMODATE with double "c" and double "m".',
    },
    {
      id: 'v7',
      question: 'Select the antonym for "CANDID":',
      options: ['Frank', 'Honest', 'Deceitful', 'Outspoken'],
      correct: 2,
      explanation: 'Candid means truthful and straightforward; deceitful is its direct antonym.',
    },
    {
      id: 'v8',
      question: 'Choose the word that best fits the blank: "His explanation was so _____ that everyone understood immediately."',
      options: ['Lucid', 'Obscure', 'Ambiguous', 'Complex'],
      correct: 0,
      explanation: 'Lucid means expressed clearly and easy to understand.',
    },
    {
      id: 'v9',
      question: 'Identify the grammatically correct sentence:',
      options: [
        'Neither of the boys were present.',
        'Neither of the boys was present.',
        'Neither of the boys are present.',
        'Neither of the boys have present.',
      ],
      correct: 1,
      explanation: '"Neither" is a singular pronoun and takes a singular verb ("was").',
    },
    {
      id: 'v10',
      question: 'Select the synonym for "PRAGMATIC":',
      options: ['Idealistic', 'Practical', 'Theoretical', 'Irrational'],
      correct: 1,
      explanation: 'Pragmatic means dealing with things sensibly and realistically (practical).',
    },
    {
      id: 'v11',
      question: 'Select the antonym for "UBIQUITOUS":',
      options: ['Rare', 'Omnipresent', 'Pervasive', 'Universal'],
      correct: 0,
      explanation: 'Ubiquitous means found everywhere; rare is its direct antonym.',
    },
    {
      id: 'v12',
      question: 'Identify the error in the sentence: "He is senior than me in the department."',
      options: ['He is', 'senior than', 'me in', 'No error'],
      correct: 1,
      explanation: 'Adjectives ending in "-ior" (senior, junior, superior) take "to" instead of "than" -> "senior to me".',
    },
    {
      id: 'v13',
      question: 'Meaning of the idiom: "Burn the midnight oil"',
      options: ['To waste electricity', 'To work late into the night', 'To start a fire', 'To celebrate late'],
      correct: 1,
      explanation: '"Burn the midnight oil" means to study or work late into the night.',
    },
    {
      id: 'v14',
      question: 'One-word substitution: "A person who looks at the bright side of things"',
      options: ['Pessimist', 'Optimist', 'Altruist', 'Egoist'],
      correct: 1,
      explanation: 'An optimist is a person who tends to be hopeful and confident about the future.',
    },
    {
      id: 'v15',
      question: 'Select the correct passive voice: "The chef prepares the dinner."',
      options: [
        'The dinner is prepared by the chef.',
        'The dinner was prepared by the chef.',
        'The dinner had prepared by the chef.',
        'The dinner is being prepared by the chef.',
      ],
      correct: 0,
      explanation: 'Simple present tense active verb "prepares" becomes "is prepared" in passive voice.',
    },
    {
      id: 'v16',
      question: 'Choose the word opposite in meaning to "BENEVOLENT":',
      options: ['Kind', 'Malevolent', 'Generous', 'Sympathetic'],
      correct: 1,
      explanation: 'Benevolent means well-meaning and kindly; malevolent means wishing evil or harm.',
    },
    {
      id: 'v17',
      question: 'Fill in the blank: "Despite the heavy rain, the event went _____ as scheduled."',
      options: ['on', 'off', 'out', 'up'],
      correct: 0,
      explanation: '"Go on" means to proceed or continue as planned.',
    },
    {
      id: 'v18',
      question: 'Select the synonym for "ELOQUENT":',
      options: ['Articulate', 'Mute', 'Hesitant', 'Quiet'],
      correct: 0,
      explanation: 'Eloquent means fluent or persuasive in speaking or writing (synonym: articulate).',
    },
    {
      id: 'v19',
      question: 'One-word substitution: "Government by a single person with absolute power"',
      options: ['Democracy', 'Autocracy', 'Oligarchy', 'Anarchy'],
      correct: 1,
      explanation: 'Autocracy is a system of government by one person with absolute power.',
    },
    {
      id: 'v20',
      question: 'Choose the correctly spelled word:',
      options: ['Entrepreneur', 'Entreprenur', 'Entreperneur', 'Entreprenuer'],
      correct: 0,
      explanation: 'The correct spelling is ENTREPRENEUR.',
    },
  ],

  technical: [
    {
      id: 't1',
      question: 'Which of the following is NOT a pillar of Object-Oriented Programming?',
      options: ['Encapsulation', 'Inheritance', 'Compilation', 'Polymorphism'],
      correct: 2,
      explanation: 'Compilation is a process executed by a compiler, not an OOP pillar (Abstraction, Encapsulation, Inheritance, Polymorphism).',
    },
    {
      id: 't2',
      question: 'What is the average time complexity of searching an element in a balanced Binary Search Tree (BST)?',
      options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
      correct: 1,
      explanation: 'Searching in a balanced BST cuts the search space in half at each step, yielding O(log N) average time complexity.',
    },
    {
      id: 't3',
      question: 'In DBMS, which ACID property ensures that transactions are committed permanently even in case of system failure?',
      options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
      correct: 3,
      explanation: 'Durability guarantees that once a transaction has committed, its results survive system failures.',
    },
    {
      id: 't4',
      question: 'Which OSI layer is responsible for end-to-end packet delivery and logical IP addressing?',
      options: ['Data Link Layer', 'Network Layer', 'Transport Layer', 'Session Layer'],
      correct: 1,
      explanation: 'The Network Layer (Layer 3) handles IP addressing and packet routing across networks.',
    },
    {
      id: 't5',
      question: 'Which Data Structure works on the Last In First Out (LIFO) principle?',
      options: ['Queue', 'Stack', 'Linked List', 'Array'],
      correct: 1,
      explanation: 'Stack pushes and pops elements from the top, operating on LIFO (Last-In-First-Out) order.',
    },
    {
      id: 't6',
      question: 'What is the HTTP status code returned for a "Resource Not Found" error?',
      options: ['200 OK', '401 Unauthorized', '404 Not Found', '500 Internal Server Error'],
      correct: 2,
      explanation: 'HTTP 404 indicates that the requested URI could not be found on the server.',
    },
    {
      id: 't7',
      question: 'Which memory section in a running process stores dynamically allocated memory (e.g. malloc / new)?',
      options: ['Stack', 'Heap', 'Data Segment', 'Code Segment'],
      correct: 1,
      explanation: 'Dynamic memory allocations during runtime are assigned from the Heap memory region.',
    },
    {
      id: 't8',
      question: 'In Git, which command creates a new branch and immediately switches to it?',
      options: ['git branch <name>', 'git checkout -b <name>', 'git merge <name>', 'git commit -b <name>'],
      correct: 1,
      explanation: '`git checkout -b <name>` (or `git switch -c <name>`) creates and checks out the new branch simultaneously.',
    },
    {
      id: 't9',
      question: 'Which database join returns ALL rows from the left table and matched rows from the right table?',
      options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'],
      correct: 1,
      explanation: 'LEFT JOIN returns all records from the left table regardless of whether there is a match in the right table.',
    },
    {
      id: 't10',
      question: 'What is the worst-case time complexity of Quick Sort?',
      options: ['O(N log N)', 'O(N)', 'O(N^2)', 'O(log N)'],
      correct: 2,
      explanation: 'When the pivot selection is poor (e.g., sorted array with first element pivot), Quick Sort degrades to O(N^2).',
    },
    {
      id: 't11',
      question: 'Which garbage collection algorithm in Java identifies objects that are no longer reachable from root references?',
      options: ['Reference Counting', 'Mark and Sweep', 'Stop the World', 'LIFO Sweeper'],
      correct: 1,
      explanation: 'Mark and Sweep identifies live root objects (Mark) and reclaims memory from unreachable objects (Sweep).',
    },
    {
      id: 't12',
      question: 'In Operating Systems, what is a Deadlock condition where each process holds a resource while waiting for another?',
      options: ['Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Circular Wait'],
      correct: 1,
      explanation: 'Hold and Wait occurs when a process holding allocated resources requests additional resources held by other processes.',
    },
    {
      id: 't13',
      question: 'Which protocol operates at the Transport Layer (Layer 4) providing reliable, connection-oriented data transfer?',
      options: ['UDP', 'IP', 'TCP', 'HTTP'],
      correct: 2,
      explanation: 'TCP (Transmission Control Protocol) is connection-oriented, reliable, and ensures ordered packet delivery.',
    },
    {
      id: 't14',
      question: 'What is the primary difference between a Process and a Thread?',
      options: [
        'Processes share memory space; threads do not',
        'Threads share memory space within a process; processes have isolated memory',
        'Threads cannot execute concurrently',
        'Processes are managed by JVM only',
      ],
      correct: 1,
      explanation: 'Threads within the same process share code, data, and OS resources, while processes execute in isolated address spaces.',
    },
    {
      id: 't15',
      question: 'In SQL, which clause is used to filter aggregated results produced by a GROUP BY clause?',
      options: ['WHERE', 'HAVING', 'ORDER BY', 'FILTER'],
      correct: 1,
      explanation: 'HAVING filters aggregated groups, whereas WHERE filters individual rows prior to aggregation.',
    },
    {
      id: 't16',
      question: 'Which data structure is optimal for implementing a LRU (Least Recently Used) Cache with O(1) get and put operations?',
      options: [
        'Array + Stack',
        'Doubly Linked List + Hash Map',
        'Binary Search Tree + Queue',
        'Heap + Hash Map',
      ],
      correct: 1,
      explanation: 'Hash Map provides O(1) key lookup, while Doubly Linked List enables O(1) removal and re-ordering of nodes.',
    },
    {
      id: 't17',
      question: 'What design pattern ensures a class has only one instance and provides a global access point to it?',
      options: ['Factory Pattern', 'Singleton Pattern', 'Observer Pattern', 'Adapter Pattern'],
      correct: 1,
      explanation: 'The Singleton Pattern restricts class instantiation to a single instance across the application lifecycle.',
    },
    {
      id: 't18',
      question: 'Which HTTP method should be idempotent and used to completely replace an existing resource?',
      options: ['POST', 'PUT', 'PATCH', 'OPTIONS'],
      correct: 1,
      explanation: 'PUT is idempotent and replaces the target resource with the uploaded payload.',
    },
    {
      id: 't19',
      question: 'What is the space complexity of Depth First Search (DFS) on a tree of height H?',
      options: ['O(1)', 'O(H)', 'O(N^2)', 'O(N log N)'],
      correct: 1,
      explanation: 'The recursion stack in DFS reaches a maximum depth equal to the height of the tree H, giving O(H) space complexity.',
    },
    {
      id: 't20',
      question: 'In Web Security, what attack occurs when a malicious script is injected into a trusted website and executed by victim browsers?',
      options: ['SQL Injection', 'Cross-Site Scripting (XSS)', 'CSRF', 'Man-in-the-Middle'],
      correct: 1,
      explanation: 'XSS (Cross-Site Scripting) involves executing unauthorized scripts in the context of a user browser session.',
    },
  ],
}
